
SELECT DEP_ID,
MAX(CASE WHEN RNUM=1 THEN SAL END) AS MAX1,
MAX(CASE WHEN RNUM=2 THEN SAL END) AS MAX2

 FROM (
SELECT DEP_ID,SAL,ROW_NUMBER() OVER(PARTITION BY DEP_ID ORDER BY SAL DESC) RNUM
 FROM EMPLOYEE ) TAB
WHERE RNUM<=2
GROUP BY DEP_ID



